### ISSUE TITLE
Make sure API request to get the current song is run on page load

### ISSUE THREAD

**Issue by chance-nelson** [chance-nelson/snowstorm-frontend#2]
Currently, the user needs to wait 3 seconds after page load to see the current song. This should be altered so that the API request is spun off immediately upon page load.

**Comment by immannino** [comment]
Hey!

I just finished wrapping up making this change and noticed a minor issue where the song metadata isn't getting updated when the song from the radio changes.

Would you want me to create a new issue for that and submit a PR for this issue separately?

**Comment by immannino** [comment]
Hi there,

I deleted my first comment because I just realized the initial load was on a `setInterval()` before and not a `setTimeout()`. I'll add back in that logic and get it to poll periodically so the song metadata works as normal. I will have a PR out soon.
