### ISSUE TITLE
API location is hardcoded

### ISSUE THREAD

**Issue by chance-nelson** [chance-nelson/snowstorm-frontend#5]
The location of a running SnowStorm instance is currently hardcoded into the player component and `main.js`. We should find a way to make this configurable at build time.

**Comment by blueish4** [comment]
Hi there!
If you want, I can take this one. I think the simplest way of doing this would be passing the hostname in as an environment variable, but I'd be open to other suggestions too.

**Comment by trepz** [comment]
Hey @blueish4 sorry I started working on this one because it was a bit annoying testing without it.
